USE DATABASE MONEY_TRANSFER_DW;

USE SCHEMA ANALYTICS;

CREATE OR REPLACE FILE FORMAT CSV_GENERIC_FORMAT
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('\\N', 'NULL', '');

DESC FILE FORMAT CSV_GENERIC_FORMAT;

