-- 1. Create warehouse
CREATE OR REPLACE WAREHOUSE COMPUTE_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- 2. Create database and schema
CREATE OR REPLACE DATABASE MONEY_TRANSFER_DW;
USE DATABASE MONEY_TRANSFER_DW;

CREATE OR REPLACE SCHEMA ANALYTICS;
USE SCHEMA ANALYTICS;
