USE DATABASE MONEY_TRANSFER_DW;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE DIM_ACCOUNT (
  ACCOUNT_KEY      NUMBER AUTOINCREMENT PRIMARY KEY,
  ACCOUNT_ID       NUMBER NOT NULL,
  HOLDER_NAME      STRING,
  EMAIL            STRING,
  STATUS           STRING,
  EFFECTIVE_DATE   DATE NOT NULL,
  EXPIRY_DATE      DATE,
  IS_CURRENT       BOOLEAN DEFAULT TRUE,
  UNIQUE(ACCOUNT_ID, EFFECTIVE_DATE)
);

CREATE OR REPLACE TABLE DIM_DATE (
  DATE_KEY         NUMBER PRIMARY KEY,
  FULL_DATE        DATE NOT NULL,
  DAY              NUMBER,
  DAY_NAME         STRING,
  DAY_OF_WEEK      NUMBER,
  WEEK             NUMBER,
  MONTH            NUMBER,
  MONTH_NAME       STRING,
  QUARTER          NUMBER,
  YEAR             NUMBER,
  FISCAL_YEAR      NUMBER,
  UNIQUE(FULL_DATE)
);

-- Populate DIM_DATE (1 year range)
INSERT INTO DIM_DATE
SELECT 
  SEQ4(),
  DATEADD(DAY, SEQ4(), '2025-01-01') AS FULL_DATE,
  DAY(DATEADD(DAY, SEQ4(), '2025-01-01')),
  DAYNAME(DATEADD(DAY, SEQ4(), '2025-01-01')),
  DAYOFWEEK(DATEADD(DAY, SEQ4(), '2025-01-01')),
  WEEKOFYEAR(DATEADD(DAY, SEQ4(), '2025-01-01')),
  MONTH(DATEADD(DAY, SEQ4(), '2025-01-01')),
  MONTHNAME(DATEADD(DAY, SEQ4(), '2025-01-01')),
  QUARTER(DATEADD(DAY, SEQ4(), '2025-01-01')),
  YEAR(DATEADD(DAY, SEQ4(), '2025-01-01')),
  YEAR(DATEADD(DAY, SEQ4(), '2025-01-01'))
FROM TABLE(GENERATOR(ROWCOUNT => 365));

DESC TABLE DIM_ACCOUNT;
DESC TABLE DIM_DATE;