USE DATABASE MONEY_TRANSFER_DW;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE FACT_TRANSACTIONS (
  TRANSACTION_KEY    NUMBER IDENTITY PRIMARY KEY,
  ACCOUNT_FROM_KEY   NUMBER NOT NULL REFERENCES DIM_ACCOUNT(ACCOUNT_KEY),
  ACCOUNT_TO_KEY     NUMBER NOT NULL REFERENCES DIM_ACCOUNT(ACCOUNT_KEY),
  DATE_KEY           NUMBER NOT NULL REFERENCES DIM_DATE(DATE_KEY),
  AMOUNT             DECIMAL(18,2) NOT NULL,
  STATUS             VARCHAR(20),
  CREATED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


DESC TABLE FACT_TRANSACTIONS;