USE DATABASE MONEY_TRANSFER_DW;
USE SCHEMA ANALYTICS;

LIST @TRANSFER_STAGE;


SELECT
  t.$1 AS ID,
  t.$2 AS BALANCE,
  t.$3 AS EMAIL,
  t.$4 AS HOLDER_NAME,
  t.$5 AS LAST_UPDATED,
  t.$6 AS STATUS
FROM @TRANSFER_STAGE/accounts1.csv (FILE_FORMAT => 'CSV_GENERIC_FORMAT') t
LIMIT 5;



SELECT
  t.$1 AS ID,
  t.$2 AS AMOUNT,
  t.$3 AS CREATEDON,
  t.$4 AS FAILURE_REASON,
  t.$5 AS FROM_ACCOUNT_ID,
  t.$6 AS IDEMPOTENCY_KEY,
  t.$7 AS STATUS,
  t.$8 AS TO_ACCOUNT_ID
FROM @TRANSFER_STAGE/transaction_logs.csv (FILE_FORMAT => 'CSV_GENERIC_FORMAT') t
LIMIT 5;

LIST @TRANSFER_STAGE;

-- REMOVE @TRANSFER_STAGE/accounts1.csv;
-- REMOVE @TRANSFER_STAGE/transaction_logs.csv