
USE DATABASE MONEY_TRANSFER_DW;
USE SCHEMA ANALYTICS;

TRUNCATE TABLE DIM_DATE;


INSERT INTO DIM_DATE (DATE_KEY, FULL_DATE, DAY, MONTH, YEAR, QUARTER)
SELECT 
  ROW_NUMBER() OVER (ORDER BY 1),
  DATEADD(DAY, ROW_NUMBER() OVER (ORDER BY 1) - 1, '2025-01-01'::DATE) AS FULL_DATE,
  DAY(DATEADD(DAY, ROW_NUMBER() OVER (ORDER BY 1) - 1, '2025-01-01'::DATE)),
  MONTH(DATEADD(DAY, ROW_NUMBER() OVER (ORDER BY 1) - 1, '2025-01-01'::DATE)),
  YEAR(DATEADD(DAY, ROW_NUMBER() OVER (ORDER BY 1) - 1, '2025-01-01'::DATE)),
  QUARTER(DATEADD(DAY, ROW_NUMBER() OVER (ORDER BY 1) - 1, '2025-01-01'::DATE))
FROM TABLE(GENERATOR(ROWCOUNT => 1095));
