USE DATABASE MONEY_TRANSFER_DW;
USE SCHEMA ANALYTICS;

TRUNCATE TABLE FACT_TRANSACTIONS;
TRUNCATE TABLE DIM_ACCOUNT;

INSERT INTO DIM_ACCOUNT (ACCOUNT_ID, HOLDER_NAME, EMAIL, STATUS, EFFECTIVE_DATE)
SELECT DISTINCT
  TRY_TO_NUMBER(account_id) AS ACCOUNT_ID,
  CASE 
    WHEN TRY_TO_NUMBER(account_id) = 1 THEN 'Primary Customer'
    WHEN TRY_TO_NUMBER(account_id) = 2 THEN 'Secondary Customer'
    ELSE 'Customer_' || TRY_TO_NUMBER(account_id)
  END AS HOLDER_NAME,
  'customer' || account_id || '@fidelity.com' AS EMAIL,
  'ACTIVE' AS STATUS,
  '2026-02-09' AS EFFECTIVE_DATE
FROM (
  SELECT $5 AS account_id FROM @TRANSFER_STAGE/transaction_logs.csv WHERE $5 IS NOT NULL
  UNION
  SELECT $8 AS account_id FROM @TRANSFER_STAGE/transaction_logs.csv WHERE $8 IS NOT NULL
)
WHERE TRY_TO_NUMBER(account_id) IS NOT NULL;

INSERT INTO FACT_TRANSACTIONS (ACCOUNT_FROM_KEY, ACCOUNT_TO_KEY, DATE_KEY, AMOUNT, STATUS)
SELECT
  daf.ACCOUNT_KEY,                    
  dat.ACCOUNT_KEY,                 
  1 AS DATE_KEY,                   
  TRY_TO_NUMBER(t.$2) AS AMOUNT,      
  COALESCE(t.$7, 'SUCCESS') AS STATUS 
FROM @TRANSFER_STAGE/transaction_logs.csv (FILE_FORMAT => 'CSV_GENERIC_FORMAT') t
LEFT JOIN DIM_ACCOUNT daf ON daf.ACCOUNT_ID = TRY_TO_NUMBER(t.$5)
LEFT JOIN DIM_ACCOUNT dat ON dat.ACCOUNT_ID = TRY_TO_NUMBER(t.$8)
WHERE TRY_TO_NUMBER(t.$2) > 0;       


SELECT 'DIM_ACCOUNT ✅' AS STATUS, COUNT(*) FROM DIM_ACCOUNT
UNION ALL
SELECT 'FACT_TRANSACTIONS ✅' AS STATUS, COUNT(*) FROM FACT_TRANSACTIONS
UNION ALL
SELECT 'SAMPLE DATA ✅' AS STATUS, COUNT(*) AS TXNS_WITH_AMOUNT FROM FACT_TRANSACTIONS WHERE AMOUNT > 0;