USE DATABASE MONEY_TRANSFER_DW;
USE SCHEMA ANALYTICS;
select * from FACT_TRANSACTIONS;

-- ===== 1. DAILY TRANSACTION VOLUME =====
SELECT
  d.FULL_DATE AS DATE,
  COUNT(*) AS TXN_COUNT,
  TO_CHAR(SUM(NULLIFZERO(f.AMOUNT)), 'FM999,999,999.99') AS TOTAL_AMOUNT,
  TO_CHAR(AVG(NULLIFZERO(f.AMOUNT)), 'FM999,999.99') AS AVG_AMOUNT
FROM FACT_TRANSACTIONS f
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
GROUP BY d.FULL_DATE
ORDER BY d.FULL_DATE DESC;

-- ===== 2. ADVANCED: ATTEMPTED vs SETTLED =====

SELECT
  d.FULL_DATE AS DATE,
  
  
  COUNT(*) AS TOTAL_ATTEMPTS,
  SUM(CASE WHEN f.STATUS = 'SUCCESS' THEN 1 ELSE 0 END) AS SUCCESS_COUNT,
  
  
  TO_CHAR(SUM(f.AMOUNT), 'FM999,999,999.00') AS ATTEMPTED_VOLUME,
  TO_CHAR(SUM(CASE WHEN f.STATUS = 'SUCCESS' THEN f.AMOUNT ELSE 0 END), 'FM999,999,999.00') AS ACTUAL_SETTLED_VOLUME

FROM FACT_TRANSACTIONS f
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
GROUP BY d.FULL_DATE
ORDER BY d.FULL_DATE DESC;

-- ===== 3. TOP ACCOUNTS =====
SELECT
  a.ACCOUNT_ID,
  a.HOLDER_NAME,
  COUNT(*) AS TXN_COUNT,
  TO_CHAR(SUM(NULLIFZERO(f.AMOUNT)), 'FM999,999,999.99') AS TOTAL_VOLUME
FROM FACT_TRANSACTIONS f
JOIN DIM_ACCOUNT a ON f.ACCOUNT_FROM_KEY = a.ACCOUNT_KEY
GROUP BY a.ACCOUNT_ID, a.HOLDER_NAME
ORDER BY TXN_COUNT DESC
LIMIT 40;

-- ===== 4. SUCCESS RATE =====

SELECT
  STATUS,
  COUNT(*) AS TXN_COUNT,
  TO_CHAR(
    ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER(), 2),
    'FM990.99'
  ) || '%' AS PERCENTAGE
FROM FACT_TRANSACTIONS
GROUP BY STATUS;


-- ===== 5. PEAK HOURS =====
SELECT
  HOUR_OF_DAY,
  COUNT(*) AS TXN_COUNT,
  TO_CHAR(SUM(NULLIFZERO(AMOUNT)), 'FM999,999.99') AS TOTAL_AMOUNT
FROM (
  SELECT DATE_PART('HOUR', CREATED_AT) AS HOUR_OF_DAY, AMOUNT
  FROM FACT_TRANSACTIONS
  WHERE AMOUNT IS NOT NULL
)
GROUP BY HOUR_OF_DAY
ORDER BY TXN_COUNT DESC;

-- ===== 6. SUMMARY METRICS =====
SELECT
  COUNT(*) AS TOTAL_TRANSACTIONS,
  COUNT(CASE WHEN STATUS = 'SUCCESS' THEN 1 END) AS SUCCESSFUL_TXNS,
  TO_CHAR(AVG(NULLIFZERO(AMOUNT)), 'FM999,999.99') AS AVG_AMOUNT,
  TO_CHAR(SUM(NULLIFZERO(AMOUNT)), 'FM999,999,999.99') AS TOTAL_VOLUME
FROM FACT_TRANSACTIONS;

-- ===== 7. TOP SENDER → RECEIVER PAIRS =====
SELECT
  a_from.HOLDER_NAME AS FROM_ACCOUNT,
  a_to.HOLDER_NAME AS TO_ACCOUNT,
  COUNT(*) AS TXN_COUNT,
  TO_CHAR(SUM(NULLIFZERO(f.AMOUNT)), 'FM999,999.99') AS TOTAL_AMOUNT
FROM FACT_TRANSACTIONS f
JOIN DIM_ACCOUNT a_from ON f.ACCOUNT_FROM_KEY = a_from.ACCOUNT_KEY
JOIN DIM_ACCOUNT a_to ON f.ACCOUNT_TO_KEY = a_to.ACCOUNT_KEY
GROUP BY a_from.HOLDER_NAME, a_to.HOLDER_NAME
ORDER BY TOTAL_AMOUNT DESC
LIMIT 10;
