USE DATABASE MONEY_TRANSFER_DW; 
USE SCHEMA ANALYTICS;
SELECT 
  COUNT(*) AS "Total Txns",
  COUNT(CASE WHEN STATUS='SUCCESS' THEN 1 END) AS "Success Txns", 
  ROUND(AVG(AMOUNT),0) AS "Avg Amount",
  '$' || TO_CHAR(SUM(AMOUNT),'FM999,999,999') AS "Total Volume"
FROM FACT_TRANSACTIONS;
