USE DATABASE MONEY_TRANSFER_DW;
USE SCHEMA ANALYTICS;
SELECT a.HOLDER_NAME AS "Account", COUNT(*) AS "TXNs", SUM(AMOUNT) AS "Volume"
FROM FACT_TRANSACTIONS f JOIN DIM_ACCOUNT a ON f.ACCOUNT_FROM_KEY = a.ACCOUNT_KEY 
GROUP BY a.HOLDER_NAME ORDER BY "Volume" DESC LIMIT 10;
