USE DATABASE MONEY_TRANSFER_DW; 
USE SCHEMA ANALYTICS;

SELECT a_from.HOLDER_NAME AS "From", a_to.HOLDER_NAME AS "To", SUM(AMOUNT) AS "Volume"
FROM FACT_TRANSACTIONS f 
JOIN DIM_ACCOUNT a_from ON f.ACCOUNT_FROM_KEY = a_from.ACCOUNT_KEY 
JOIN DIM_ACCOUNT a_to ON f.ACCOUNT_TO_KEY = a_to.ACCOUNT_KEY 
GROUP BY a_from.HOLDER_NAME, a_to.HOLDER_NAME ORDER BY "Volume" DESC LIMIT 5;
