USE DATABASE MONEY_TRANSFER_DW;
USE SCHEMA ANALYTICS;

SELECT a_from.HOLDER_NAME AS "From", a_to.HOLDER_NAME AS "To", f.AMOUNT, f.STATUS, f.CREATED_AT
FROM FACT_TRANSACTIONS f 
JOIN DIM_ACCOUNT a_from ON f.ACCOUNT_FROM_KEY = a_from.ACCOUNT_KEY 
JOIN DIM_ACCOUNT a_to ON f.ACCOUNT_TO_KEY = a_to.ACCOUNT_KEY 
ORDER BY f.CREATED_AT DESC LIMIT 10;
